# Generated by Django 4.1.2 on 2022-10-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.CharField(choices=[('0', 'student'), ('1', 'curator'), ('2', 'admin')], default='student', max_length=10),
        ),
    ]
