# Generated by Django 4.1.2 on 2022-10-27 10:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.UUID('0311513b-543f-4f13-8a9a-efec7e47922f'))),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.UUID('e46eb15f-13a3-47bb-b9a3-28cf6a3829bb'))),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudyingDirection',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.UUID('582daf5f-83f7-4cce-b786-78b4f4cc5ee6'))),
                ('name', models.CharField(max_length=255)),
                ('disciplines', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.discipline')),
            ],
        ),
    ]
