# Generated by Django 4.1.2 on 2022-10-27 10:41

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studyingdirection',
            name='groups',
            field=models.ManyToManyField(to='core.studentgroup'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.UUID('eb03e71d-67ce-41c1-82ba-ebab37227fc8')),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.UUID('56a04ec7-21d6-4e46-8bbb-149f85ccec20')),
        ),
        migrations.AlterField(
            model_name='studyingdirection',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.UUID('901244f4-12bf-4913-b9a4-360f136410c2')),
        ),
    ]
