# Generated by Django 4.1.2 on 2022-10-27 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studentgroup_students_studyingdirection_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.UUID('e120fa1a-b4e9-48f8-97da-d54077b14e19')),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.UUID('7dafc912-e48f-4f89-a847-4ae930fd5117')),
        ),
        migrations.AlterField(
            model_name='studyingdirection',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.UUID('d6475279-5983-483b-873c-847b18355c73')),
        ),
    ]
