# Generated by Django 4.1.2 on 2022-10-27 13:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_discipline_id_alter_studentgroup_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.UUID('30670f69-456a-44b6-af2b-7beb2a471f20')),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.UUID('02034208-2f1c-4cd9-89c6-e4ed721a73ac')),
        ),
        migrations.RemoveField(
            model_name='studyingdirection',
            name='groups',
        ),
        migrations.AlterField(
            model_name='studyingdirection',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.UUID('181b497f-b1cd-4e2f-b843-447f9afa55dd')),
        ),
        migrations.AddField(
            model_name='studyingdirection',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.studentgroup'),
        ),
    ]
