# Generated by Django 4.1.2 on 2022-10-27 13:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_discipline_id_alter_studentgroup_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.UUID('362146b4-9e8d-4c13-97eb-3aca1be9ff8c')),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.UUID('dc01d087-bbcf-49d2-9e2a-3596c6dffa8b')),
        ),
        migrations.AlterField(
            model_name='studyingdirection',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.UUID('777424d1-b1cc-47be-b99f-5c434678080d')),
        ),
    ]
